### ISSUE TITLE
Ubuntu Zesty

### ISSUE THREAD

**Issue by nbah07** [faf0/sct#1]
Hello!
Would this tool compile in Ubuntu 17.04?
Does the distro 17.04 package still has this problems you mentioned in README.md, e.g. memory leak?
I am using the distro 17.04 package, untill now, I noticed it doesn't change the VGA display color temperature on my notebook. Don't know about those other issues.
Do you recommend xcalib or another tool for color inversion (black bg the screen)? I want to try the feature of these tools, I am having sleeping issues.
Have a great time

**Comment by faf0** [comment]
Hello,
This tool wasn't tested on Ubuntu 17.04 but it shouldn't be hard to make this tool run on any distribution that uses the X Windows System. This tool does _not_ have the memory leak problem. In fact, this fork of the tool fixes the problems mentioned in `README.md`.
Hope that helps!

**Comment by nbah07** [comment]
I'm glad you've responded.
I understand your fork/tool fix some issues. I should contact the maintainer ubuntu-motu@lists.ubuntu.com

**Comment by nbah07** [comment]
Hello,
How to view current sct status, the last value inputed? I've set a cron job which applies color temperatures in hourly steps. the highest value is at 12:00AM, so it decreases when moving away from this hour, both backwards and forwards. I want to check if is it working what I've done.

**Comment by faf0** [comment]
Hi @nbah07, you could write the input values to a file when the cron job runs. You may want to consider having cron call a shell script which computes the input values for sct, calls sct, and writes the input values to a file. Unfortunately, there is no way to query the status of sct since sct does not keep running in the background.

**Comment by zvezdochiot** [comment]
@maowm say> How to view current sct status, the last value inputed?

PR #5 (Read current temperature)

**Comment by faf0** [comment]
Closing this one, though @nbah07 please don't hesitate to reopen it if you have another related question.
