### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by zvezdochiot** [faf0/sct#11]
https://github.com/faf0/sct/blob/a38a0df3f85e0c437de3a28cf1627bcae68ef4ff/LICENSE#L1-L11

More standard view:

Public Domain Mark 1.0:

https://github.com/ImageProcessing-ElectronicPublications/jpegrescan-perl/blob/master/LICENSE

https://creativecommons.org/licenses/mark/1.0/

Not?

**Comment by faf0** [comment]
Thanks, let's add a `LICENSE` file

**Comment by zvezdochiot** [comment]
@faf0 say> Thanks, let's add a LICENSE file

Not add, but replace with a more standard one.

Replace?

**Comment by zvezdochiot** [comment]
PR #10 Commit https://github.com/faf0/sct/pull/10/commits/f65932e6da47e857b4aaf7ab8ab301886ecc87c7

**Comment by zvezdochiot** [comment]
Hi @faf0 .

At the moment, on github, instead of ["PDM"](https://github.com/faf0/sct/blob/master/LICENSE), it is customary to use ["The Unlicense"](https://github.com/Geo-Linux-Calculations/geofindkey/blob/master/LICENSE). See list [liceses](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository).

**Comment by faf0** [comment]
@zvezdochiot , changed to Unlicense in https://github.com/faf0/sct/pull/27 .
