### ISSUE TITLE
restarting the app after computer goes to sleep

### ISSUE THREAD

**Issue by willsn0w** [faf0/sct#15]
Hello!

This is the only app I coud make work on Deepin. Neither F.lux or Redshift did work consistently. But I noticed that when I'm away and my pc sleeps, sct stops running. You need to type the command again.

#2  I noticed this app is a little bit yellow-ish than the other both I cited and Windows 10 have a more orange-ish color without going to 2000-1000 values. Is it possible to edit this range of colors?

Great app and simple to use, I was almost giving up to go back to Pop!_OS because of the native solution on night light, haha :)

**Comment by faf0** [comment]
Hi @willsn0w !

> But I noticed that when I'm away and my pc sleeps, sct stops running. You need to type the command again.

You might look into having systemd (or the service runsystem that you use) run the command automatically when the computer awakens from sleep. E.g., https://wiki.archlinux.org/index.php/Deepin_Desktop_Environment#No_background_after_resuming_from_standby

> Is it possible to edit this range of colors?

The color temperature settings are computed to approximately match those from the table hardcoded in Redshift (see https://github.com/jonls/redshift/blob/04760afe31bff5b26cf18fe51606e7bdeac15504/src/colorramp.c#L30-L273). Previously, the values were copied from the Redshift table: https://github.com/faf0/sct/pull/10 . Maybe tweaking the constants here (and then recompiling) allows you to achieve the results you're looking for: https://github.com/faf0/sct/blob/eaf655e2f5fd8be37997f6cd76a857c54e8d7288/xsct.c#L43-L63

**Comment by zvezdochiot** [comment]
Hi @willsn0w .

:link: See http://www.vendian.org/mncharity/dir3/blackbody/UnstableURLs/bbr_color.html

Hi @faf0 .

:question: Maybe add this link in README?

**Comment by willsn0w** [comment]
Hi @zvezdochiot, this sure helps a lot with the colour scheme! Thank you very much!

**Comment by faf0** [comment]
@zvezdochiot @willsn0w Created a PR to include the suggested link in the README: https://github.com/faf0/sct/pull/17

**Comment by faf0** [comment]
Closing this issue, but @willsn0w feel free to reopen it if you have any comments.
