### ISSUE TITLE
Release of xsct?

### ISSUE THREAD

**Issue by sunweaver** [faf0/sct#19]
Hi,

I'd like to bring this package to Debian (as an alternative to the sct package that Debian currently has), as I see this package being more/better maintained than setcolortemperature upstream. Also the mult-display support is a good to have feature.

For tracking upstream changes, it is really helpful to package only released versions. Do you think, you could make a release of xsct as it currently is and prepare follow-up release whenever you see fit?

For me, a release version tag on this Git repo is sufficient as a release.

Thanks,
Mike (aka sunweaver at debian.org)

**Comment by faf0** [comment]
Hi Mike,

> Do you think, you could make a release of xsct as it currently is and prepare follow-up release whenever you see fit?

Absolutely. There have been different versions of this project already, but no corresponding git tags. I've tagged the current state of master as version 1.6, which is consistent with CHANGELOG:
https://github.com/faf0/sct/blob/f73e8736b3b03eb36d3c8ac96c047a2ddafa301b/CHANGELOG#L3

Also, I appreciate your efforts to release xsct as a Debian package. Thank you!

Best,
Fabian

**Comment by zvezdochiot** [comment]
Hi @sunweaver .

See also https://sourceforge.net/projects/debiannoofficial/files/wheezy-update/x11/xsct_1.5-wheezy_i386.deb

PS: To manipulate the package use: https://github.com/BASH-Auto-Tools/bash-deb-build

**Comment by sunweaver** [comment]
> Hi @sunweaver .
> 
> See also https://sourceforge.net/projects/debiannoofficial/files/wheezy-update/x11/xsct_1.5-wheezy_i386.deb
> 
> PS: To manipulate the package use: https://github.com/BASH-Auto-Tools/bash-deb-build

I created the DEB package manually now. Thanks for the hint.

**Comment by faf0** [comment]
Thanks, @sunweaver .

Version 1.7 was released recently and I expect version 1.8 to be released soon.
