### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by helionmelion** [faf0/sct#2]
I like how this little program handles the color temp, comparing with redshift - for instance, the cursor color is also modified; they turn every color to red - feels much better.
1 - Is there any project to add brightness control to it?
Tried to use redshift to manage brightness and sct the color temp, but one interferes with other - no deal.
2 - How I know if sct is loaded since I didnt figure out its process name in top?

thank you very much.

**Comment by faf0** [comment]
1) There is xbacklight. For some other possibilities, check out https://wiki.archlinux.org/index.php/backlight It would be nice to leverage the X Server API and add a brightness command line flag to sct.
2) The process changes the colors and then exits, so the process is only running for a short time. You can run the sct regularly by scheduling a cron job.

**Comment by helionmelion** [comment]
> There is xbacklight. For some other possibilities, check out https://wiki.archlinux.org/index.php/backlight It would be nice to leverage the X Server API and add a brightness command line flag to sct.

Unfortunately my monitor does not support DDCCONTROL - that was the perfect choice for brightness control and who knows, handling the color IMHO. 

> The process changes the colors and then exits, so the process is only running for a short time. You can run the sct regularly by scheduling a cron job.

This is wonderful, congratulations for this software.
