### ISSUE TITLE
Config example request, how to set-up sct at boot-up?

### ISSUE THREAD

**Issue by lorn10** [faf0/sct#23]
A hello from my side!

At first I want to say a BIG thanks for this great little `sct` program. :+1: 

Here now follows some type of technical request regarding a simple "auto-boot example" of `sct`. I was unable to find one.

I am on Kubuntu 20.04 LTS and `sct` works superb. However, I couldn't figure out how to config `sudo sct 7500` automatically at startup. At the moment I have to run this command (from terminal) at every reboot. 

So what would be the most logical way to implement this automatically? This is most likely an easy task, - well I am still a Linux noob. ;-)

Thanks for any hints!

**Comment by zvezdochiot** [comment]
@lorn10 say:
>`sudo sct 7500`

`sudo`? Are you sure you need this? What for?

**Comment by faf0** [comment]
`sct 7500` without `sudo` should be sufficient.

As for the executing the command on startup, you could look into https://www.reddit.com/r/kde/comments/9edciu/daily_tip_kde_provides_a_scheduled_task_interface/ . I don't use Kubuntu so I haven't tried this myself.

Closing this issue out, as executing a command when the operating system boots is not a functionality that sct should provide. This functionality should be provided by operating system tooling.

**Comment by lorn10** [comment]
Thanks for the fast replay with the tip regarding the "scheduled task interface for KDE". :+1:  

Yes, it looks that `sudo` is in this context here not really necessary.... I thought that `sct` runs as a low-level "system command" and needs it when started at boot. ;-)
