### ISSUE TITLE
Shields?

### ISSUE THREAD

**Issue by zvezdochiot** [faf0/sct#26]
Hi @faf0 .

Maybe added in head README.md shields?
```markdown
![GitHub release (latest by date)](https://img.shields.io/github/v/release/faf0/sct)
![GitHub Release Date](https://img.shields.io/github/release-date/faf0/sct)
![GitHub repo size](https://img.shields.io/github/repo-size/faf0/sct)
![GitHub all releases](https://img.shields.io/github/downloads/faf0/sct/total)
![GitHub](https://img.shields.io/github/license/faf0/sct)  
```
![GitHub release (latest by date)](https://img.shields.io/github/v/release/faf0/sct) ![GitHub Release Date](https://img.shields.io/github/release-date/faf0/sct) ![GitHub repo size](https://img.shields.io/github/repo-size/faf0/sct) ![GitHub all releases](https://img.shields.io/github/downloads/faf0/sct/total) ![GitHub](https://img.shields.io/github/license/faf0/sct)

**Comment by faf0** [comment]
Thanks, @zvezdochiot . I opened https://github.com/faf0/sct/pull/29 .
