### ISSUE TITLE
Could you implement a software brightness feature?

### ISSUE THREAD

**Issue by pinbuck** [faf0/sct#32]
For example I use xrandr to change brightness:

xrandr --output DVI-D-0 --brightness 0.6

xrandr --output DVI-D-0 --brightness 1.0

however sct simply overrides the software brightness. Possibly could you either make these not impede eachother, or integrate that functionality?
For example, gummy has similar functionality:
https://github.com/?q=gummy
however he doesn't have support for fedora currently.

**Comment by zvezdochiot** [comment]
Hi @faf0 .

Maybe use `gamam` as `brightness`?:
https://github.com/faf0/sct/blob/1bfe07511820065d8bed2045776e25b6f42a8793/xsct.c#L85-L86
Use:
```c
struct temp_status
{
    int temp;
    float brightness;
};
```
for return?

**Comment by pinbuck** [comment]
I found this outdated version of sct that has brightness added as an option so I started using it:
https://github.com/mgudemann/sct
It practically does what I mentioned and works, but it doesn't seem to be actively maintained while this one is
I cleaned up my comments and I'll move it to a different post, my bad.

**Comment by faf0** [comment]
Thanks, @zvezdochiot , for implementing a brightness feature in https://github.com/X11-good-tools/xsct/commit/c0fe8a4bf281680f3fd3f8c13e2eae76a06e185b . Besides a couple of minor things, the implementation looks very good! Please feel free to open a pull request!

**Comment by faf0** [comment]
> I had to figure out how to compile this again, turns out I was missing at least one dependency listed in here: [go-gl/glfw#158](https://github.com/go-gl/glfw/issues/158) Could you please post a list of dependencies?
> 
> [test.txt](https://github.com/faf0/sct/files/9312553/test.txt)
> 
> I found an outdated version of sct that has brightness as an option and i started using it: https://github.com/mgudemann/sct
> 
> Is it possible that you could supply a precompiled binary for every release? Building is fine and should be available, but having that be the only method of acquisition it means users will have to use one more command and download more packages to be able to get to the point where they can use the working piece of software. I'm currently on fedora trying to find a simple alternative to gummy since that doesn't seem to have good support for fedora. I'm not saying "package it as a deb, rpm, or appimage" because that's more or less unnecessary, the xsct executable works just fine by itself.

We have this discussion separately from the brightness discussion. Please feel free to open a separate issue in this project with the exact version number of the operating system you are seeing the build error and the output of the build command.

Regarding precompiled binaries, I think these should either come from distributions directly or the binary should be compiled and linked against the libraries of the corresponding system.

**Comment by zvezdochiot** [comment]
Hi @faf0 .

See before PR.

**Comment by pinbuck** [comment]
I was able to compile it without the errors after reading somebody else's post. I likely accidentally uninstalled a compiler package or something. I solved my issue after a few hours after I posted that unrelated second comment. I'll leave this issue open unless or until you want to close it.
I'm confused, is this project being moved to X11-good-tools/xsct ?
update: using 1.9 x11-good-tools build from zvez, thanks for the responses. I would consider this as solved but zvez is using this to show progress.

**Comment by faf0** [comment]
@zvezdochiot contributed https://github.com/faf0/sct/pull/33 . Thanks!

**Comment by pinbuck** [comment]
is faf0's sct the exact same thing as xsct in zvezdochiot's good x11 tools?

**Comment by faf0** [comment]
@pinbuck , X11-good-tools/xsct is a fork of faf0/sct .

The latest commits as of now are identical:
- https://github.com/X11-good-tools/xsct/commit/f2aa7c80a8bb2af9c5755aedbcc594a841af6713
- https://github.com/faf0/sct/commit/f2aa7c80a8bb2af9c5755aedbcc594a841af6713
