### ISSUE TITLE
Incompatibility with Ubuntu 22.04 due to Wayland

### ISSUE THREAD

**Issue by j-silv** [faf0/sct#35]
Hi there! 

I recently upgraded from Ubuntu 20.04 to Ubuntu 22.04 and to my grand dismay, this program (xsct) no longer worked. I did some digging and found out that it is because the newer versions of Ubuntu switched to Wayland as their windowing system, and this script doesn't play well with that.

A workaround is just switching Ubuntu to use Xorg, as per [this guide](https://beebom.com/how-switch-between-wayland-xorg-ubuntu/).

I've read that there is a compatibility layer called Xwayland. Would it be a lot of work to get this script to work under that compatibility layer? (Sorry I don't know much about these systems). This is such a neat program, and super practical for changing the color temperature and brightness of my external monitors.

**Comment by zvezdochiot** [comment]
Hi @j-silv .

Use https://github.com/jonls/redshift. `Xsct` for only `X11`.

**Comment by faf0** [comment]
Closing as Wayland support is not planned for this tool.
