### ISSUE TITLE
Approximation or table?

### ISSUE THREAD

**Issue by zvezdochiot** [faf0/sct#9]
@faf0 , table `redshift` is well approximated by logarithmic functions (R2 = 0.994 ÷ 0.999). Maybe it's worth replacing it with functions.

https://i87.fastpic.ru/big/2019/0806/62/b61acfc5f395010263a4a43fab0b7862.png

**Comment by faf0** [comment]
Thanks! I like that idea!

**Comment by zvezdochiot** [comment]
@faf0 say> Thanks! I like that idea!

PR #10
